backend:
  name: github
  repo: berkeleymt/berkeley.mt
  branch: main

collections:
  - name: "news"
    label: "News"
    folder: "content/news"
    format: toml-frontmatter
    create: true
    slug: "{{date | date('YYYY-MM-DD')}}_{{slug}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
        time_format: false
      - label: "Body"
        name: "body"
        widget: "markdown"

media_folder: "static/assets/"
