name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: https://berkeley.mt/
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v11

      - name: Setup Nix build cache
        uses: DeterminateSystems/magic-nix-cache-action@v6

      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@v7

      - name: Build website for production
        run: nix build .#for-production

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: result
          path: result/

  deploy:
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: https://berkeley.mt/
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: result

      - name: Deploy to OCF
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avPh --delete --exclude=.htaccess
          path: .
          remote_path: ~/public_html/new
          remote_host: tsunami.ocf.berkeley.edu
          remote_user: bmt
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
